# Generated by Django 2.0.7 on 2018-08-03 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monserver', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='server',
            name='dc',
        ),
        migrations.RemoveField(
            model_name='status',
            name='server',
        ),
        migrations.RemoveField(
            model_name='status',
            name='service',
        ),
        migrations.RemoveField(
            model_name='status',
            name='version',
        ),
        migrations.DeleteModel(
            name='DC',
        ),
        migrations.DeleteModel(
            name='Server',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.DeleteModel(
            name='Status',
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
