# Generated by Django 2.0.7 on 2018-08-03 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='dc',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dc', to='api.DC'),
        ),
    ]
