# Generated by Django 2.0.7 on 2018-11-20 15:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_report_dc'),
    ]

    operations = [
        migrations.CreateModel(
            name='vCenter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vcenter_name', models.CharField(default='', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='winENV',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('winenv_name', models.CharField(default='', max_length=50, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='winnode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('node_name', models.CharField(default='', max_length=50, unique=True)),
                ('java_version', models.CharField(max_length=100)),
                ('chrome_verson', models.CharField(max_length=100)),
                ('firefox_version', models.CharField(max_length=100)),
                ('chromedriver_version', models.CharField(max_length=100)),
                ('gecko_version', models.CharField(max_length=100)),
                ('selenium_version', models.CharField(max_length=100)),
                ('python_version', models.CharField(max_length=100)),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('vcenter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vCenter', to='api.vCenter')),
                ('winenv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='winenv', to='api.winENV')),
            ],
        ),
    ]
