# Generated by Django 2.0.7 on 2018-11-20 16:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_winnode_loaddata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='winnode',
            old_name='chrome_verson',
            new_name='chrome_version',
        ),
    ]
