# Generated by Django 2.0.7 on 2018-11-21 12:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20181120_1619'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='winnode',
            name='created',
        ),
        migrations.RemoveField(
            model_name='winnode',
            name='status',
        ),
        migrations.AlterField(
            model_name='winnode',
            name='updated',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
