# Generated by Django 2.0.7 on 2018-11-26 11:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20181121_1239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnode',
            name='chrome_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='chromedriver_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='firefox_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='gecko_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='java_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='node_name',
            field=models.CharField(db_index=True, default='', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='python_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='selenium_version',
            field=models.CharField(db_index=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='updated',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
    ]
