# Generated by Django 2.0.7 on 2018-11-29 16:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20181128_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='winnode',
            name='datastore_name',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='datastore', to='api.Datastore'),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='esxi_host',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='esxi', to='api.ESXiHost'),
        ),
        migrations.AlterField(
            model_name='winnode',
            name='windows_version',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='winver', to='api.WindowsVersion'),
        ),
    ]
