version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'monuser'
      POSTGRES_PASSWORD: 'monpasswd'
      POSTGRES_DB: 'monserver'
    restart: always
    ports:
        - 5432:5432

  mon:
    build:
      context: ./
      dockerfile: ./mon.Dockerfile
    image: django_image
    restart: always
    volumes:
      - django_static:/mon/mon/static
    depends_on:
      - db

  nginx:
    build:
        context: ./
        dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    restart: always
    volumes:
      - django_static:/code/static
    depends_on:
      - mon

  redis:
    image: redis:4
    restart: always

  celery-beat:
    build:
      context: ./
      dockerfile: celery_beat.Dockerfile
    restart: always
    depends_on:
      - redis

  celery-worker:
    build:
      context: ./
      dockerfile: celery_worker.Dockerfile
    restart: always
    depends_on:
      - redis


volumes:
  django_static:
