version: '3'
services:
  db:
    image: postgres:9.6
    environment:
      POSTGRES_USER: 'monuser'
      POSTGRES_PASSWORD: 'monpasswd'
      POSTGRES_DB: 'monserver'
    restart: always
    ports:
        - 5432:5432


  mon:
    build:
      context: ./
      dockerfile: ./mon.Dockerfile
    image: django_image
    restart: always
    depends_on:
      - db

  nginx:
    build:
        context: ./
        dockerfile: nginx.Dockerfile
    ports:
      - 80:80
    restart: always
    depends_on:
      - mon