# Generated by Django 2.0.7 on 2018-08-03 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20180803_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='server',
            name='dc',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='dc', to='api.DC'),
        ),
        migrations.AlterField(
            model_name='status',
            name='version',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Version',
        ),
    ]
