# Generated by Django 2.0.7 on 2018-08-07 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20180803_1405'),
    ]

    operations = [
        migrations.AlterField(
            model_name='status',
            name='version',
            field=models.CharField(max_length=100),
        ),
    ]
