# Generated by Django 2.0.7 on 2018-07-30 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monserver', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='status',
            unique_together=set(),
        ),
    ]
